### PR TITLE
Dotnet5

### PR DESCRIPTION
**Pull request by KnicKnic**
## Description
move to dotnet 5
breaking changes described at https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0

## Related issues
[AB#78704](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78704)

## Testing
Relying on CI

### CODE REVIEW

**Comment by brandonpollett** [comment]
I believe you'll also need to update the arm templates - https://github.com/microsoft/dicom-server/blob/dcc067d7b2628e68cca9bebfbd98fe8aa5505746/samples/templates/default-azuredeploy.json#L236

**Comment by KnicKnic** [comment]
/azp run


> I believe you'll also need to update the arm templates -
> 
> https://github.com/microsoft/dicom-server/blob/dcc067d7b2628e68cca9bebfbd98fe8aa5505746/samples/templates/default-azuredeploy.json#L236

correct, fixed

**Review by brandonpollett — APPROVED** [review]

**Pull request merged**
